#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

uint8_t get_value(char c) {
	if (c >= 0x30 && c <= 0x39) return c - 0x30;
	else if (c >= 0x41 && c <= 0x46) return c - 0x41 + 0xA;
	else if (c >= 0x61 && c <= 0x66) return c - 0x61 + 0xA;
	else exit(-1);
}

/// get a hexadecimal ascii encoded byte from stdin (ignoring spaces and newlines)
uint8_t next() {
	int c1;
	do {
		c1 = getchar();
		if (c1 == EOF) exit(0);
	 } while (c1 == 0x0A || c1 == 0x20);

	int c2;
	do {
		c2 = getchar();
		if (c2 == EOF) exit(0);
	 } while (c2 == 0x0A || c2 == 0x20);

	uint8_t num = get_value(c1)*0x10 + get_value(c2);
	return num;
}

/// get a 24 bit value little-endian value from stdin
uint32_t next_value() {
	uint32_t nn = next();
	uint32_t mm = next();
	uint32_t Mm = next();
	return Mm*0x10000 + mm*0x100 + nn;
}

void print_cb() {
	uint8_t i = next();
	if (i == 0x00) printf("rlc  b");
	else if (i == 0x01) printf("rlc  c");
	else if (i == 0x02) printf("rlc  d");
	else if (i == 0x03) printf("rlc  e");
	else if (i == 0x04) printf("rlc  h");
	else if (i == 0x05) printf("rlc  l");
	else if (i == 0x06) printf("rlc  (hl)");
	else if (i == 0x07) printf("rlc  a");
	else if (i == 0x08) printf("rrc  b");
	else if (i == 0x09) printf("rrc  c");
	else if (i == 0x0A) printf("rrc  d");
	else if (i == 0x0B) printf("rrc  e");
	else if (i == 0x0C) printf("rrc  h");
	else if (i == 0x0D) printf("rrc  l");
	else if (i == 0x0E) printf("rrc  (hl)");
	else if (i == 0x0F) printf("rrc  a");
	else if (i == 0x10) printf("rl   b");
	else if (i == 0x11) printf("rl   c");
	else if (i == 0x12) printf("rl   d");
	else if (i == 0x13) printf("rl   e");
	else if (i == 0x14) printf("rl   h");
	else if (i == 0x15) printf("rl   l");
	else if (i == 0x16) printf("rl   (hl)");
	else if (i == 0x17) printf("rl   a");
	else if (i == 0x18) printf("rr   b");
	else if (i == 0x19) printf("rr   c");
	else if (i == 0x1A) printf("rr   d");
	else if (i == 0x1B) printf("rr   e");
	else if (i == 0x1C) printf("rr   h");
	else if (i == 0x1D) printf("rr   l");
	else if (i == 0x1E) printf("rr   (hl)");
	else if (i == 0x1F) printf("rr   a");
	else if (i == 0x20) printf("sla  b");
	else if (i == 0x21) printf("sla  c");
	else if (i == 0x22) printf("sla  d");
	else if (i == 0x23) printf("sla  e");
	else if (i == 0x24) printf("sla  h");
	else if (i == 0x25) printf("sla  l");
	else if (i == 0x26) printf("sla  (hl)");
	else if (i == 0x27) printf("sla  a");
	else if (i == 0x28) printf("sra  b");
	else if (i == 0x29) printf("sra  c");
	else if (i == 0x2A) printf("sra  d");
	else if (i == 0x2B) printf("sra  e");
	else if (i == 0x2C) printf("sra  h");
	else if (i == 0x2D) printf("sra  l");
	else if (i == 0x2E) printf("sra  (hl)");
	else if (i == 0x2F) printf("sra  a");
	else if (i == 0x38) printf("srl  b");
	else if (i == 0x39) printf("srl  c");
	else if (i == 0x3A) printf("srl  d");
	else if (i == 0x3B) printf("srl  e");
	else if (i == 0x3C) printf("srl  h");
	else if (i == 0x3D) printf("srl  l");
	else if (i == 0x3E) printf("srl  (hl)");
	else if (i == 0x3F) printf("srl  a");
	else if (i == 0x40) printf("bit  0,b");
	else if (i == 0x41) printf("bit  0,c");
	else if (i == 0x42) printf("bit  0,d");
	else if (i == 0x43) printf("bit  0,e");
	else if (i == 0x44) printf("bit  0,h");
	else if (i == 0x45) printf("bit  0,l");
	else if (i == 0x46) printf("bit  0,(hl)");
	else if (i == 0x47) printf("bit  0,a");
	else if (i == 0x48) printf("bit  1,b");
	else if (i == 0x49) printf("bit  1,c");
	else if (i == 0x4A) printf("bit  1,d");
	else if (i == 0x4B) printf("bit  1,e");
	else if (i == 0x4C) printf("bit  1,h");
	else if (i == 0x4D) printf("bit  1,l");
	else if (i == 0x4E) printf("bit  1,(hl)");
	else if (i == 0x4F) printf("bit  1,a");
	else if (i == 0x50) printf("bit  2,b");
	else if (i == 0x51) printf("bit  2,c");
	else if (i == 0x52) printf("bit  2,d");
	else if (i == 0x53) printf("bit  2,e");
	else if (i == 0x54) printf("bit  2,h");
	else if (i == 0x55) printf("bit  2,l");
	else if (i == 0x56) printf("bit  2,(hl)");
	else if (i == 0x57) printf("bit  2,a");
	else if (i == 0x58) printf("bit  3,b");
	else if (i == 0x59) printf("bit  3,c");
	else if (i == 0x5A) printf("bit  3,d");
	else if (i == 0x5B) printf("bit  3,e");
	else if (i == 0x5C) printf("bit  3,h");
	else if (i == 0x5D) printf("bit  3,l");
	else if (i == 0x5E) printf("bit  3,(hl)");
	else if (i == 0x5F) printf("bit  3,a");
	else if (i == 0x60) printf("bit  4,b");
	else if (i == 0x61) printf("bit  4,c");
	else if (i == 0x62) printf("bit  4,d");
	else if (i == 0x63) printf("bit  4,e");
	else if (i == 0x64) printf("bit  4,h");
	else if (i == 0x65) printf("bit  4,l");
	else if (i == 0x66) printf("bit  4,(hl)");
	else if (i == 0x67) printf("bit  4,a");
	else if (i == 0x68) printf("bit  5,b");
	else if (i == 0x69) printf("bit  5,c");
	else if (i == 0x6A) printf("bit  5,d");
	else if (i == 0x6B) printf("bit  5,e");
	else if (i == 0x6C) printf("bit  5,h");
	else if (i == 0x6D) printf("bit  5,l");
	else if (i == 0x6E) printf("bit  5,(hl)");
	else if (i == 0x6F) printf("bit  5,a");
	else if (i == 0x70) printf("bit  6,b");
	else if (i == 0x71) printf("bit  6,c");
	else if (i == 0x72) printf("bit  6,d");
	else if (i == 0x73) printf("bit  6,e");
	else if (i == 0x74) printf("bit  6,h");
	else if (i == 0x75) printf("bit  6,l");
	else if (i == 0x76) printf("bit  6,(hl)");
	else if (i == 0x77) printf("bit  6,a");
	else if (i == 0x78) printf("bit  7,b");
	else if (i == 0x79) printf("bit  7,c");
	else if (i == 0x7A) printf("bit  7,d");
	else if (i == 0x7B) printf("bit  7,e");
	else if (i == 0x7C) printf("bit  7,h");
	else if (i == 0x7D) printf("bit  7,l");
	else if (i == 0x7E) printf("bit  7,(hl)");
	else if (i == 0x7F) printf("bit  7,a");
	else if (i == 0x80) printf("res  0,b");
	else if (i == 0x81) printf("res  0,c");
	else if (i == 0x82) printf("res  0,d");
	else if (i == 0x83) printf("res  0,e");
	else if (i == 0x84) printf("res  0,h");
	else if (i == 0x85) printf("res  0,l");
	else if (i == 0x86) printf("res  0,(hl)");
	else if (i == 0x87) printf("res  0,a");
	else if (i == 0x88) printf("res  1,b");
	else if (i == 0x89) printf("res  1,c");
	else if (i == 0x8A) printf("res  1,d");
	else if (i == 0x8B) printf("res  1,e");
	else if (i == 0x8C) printf("res  1,h");
	else if (i == 0x8D) printf("res  1,l");
	else if (i == 0x8E) printf("res  1,(hl)");
	else if (i == 0x8F) printf("res  1,a");
	else if (i == 0x90) printf("res  2,b");
	else if (i == 0x91) printf("res  2,c");
	else if (i == 0x92) printf("res  2,d");
	else if (i == 0x93) printf("res  2,e");
	else if (i == 0x94) printf("res  2,h");
	else if (i == 0x95) printf("res  2,l");
	else if (i == 0x96) printf("res  2,(hl)");
	else if (i == 0x97) printf("res  2,a");
	else if (i == 0x98) printf("res  3,b");
	else if (i == 0x99) printf("res  3,c");
	else if (i == 0x9A) printf("res  3,d");
	else if (i == 0x9B) printf("res  3,e");
	else if (i == 0x9C) printf("res  3,h");
	else if (i == 0x9D) printf("res  3,l");
	else if (i == 0x9E) printf("res  3,(hl)");
	else if (i == 0x9F) printf("res  3,a");
	else if (i == 0xA0) printf("res  4,b");
	else if (i == 0xA1) printf("res  4,c");
	else if (i == 0xA2) printf("res  4,d");
	else if (i == 0xA3) printf("res  4,e");
	else if (i == 0xA4) printf("res  4,h");
	else if (i == 0xA5) printf("res  4,l");
	else if (i == 0xA6) printf("res  4,(hl)");
	else if (i == 0xA7) printf("res  4,a");
	else if (i == 0xA8) printf("res  5,b");
	else if (i == 0xA9) printf("res  5,c");
	else if (i == 0xAA) printf("res  5,d");
	else if (i == 0xAB) printf("res  5,e");
	else if (i == 0xAC) printf("res  5,h");
	else if (i == 0xAD) printf("res  5,l");
	else if (i == 0xAE) printf("res  5,(hl)");
	else if (i == 0xAF) printf("res  5,a");
	else if (i == 0xB0) printf("res  6,b");
	else if (i == 0xB1) printf("res  6,c");
	else if (i == 0xB2) printf("res  6,d");
	else if (i == 0xB3) printf("res  6,e");
	else if (i == 0xB4) printf("res  6,h");
	else if (i == 0xB5) printf("res  6,l");
	else if (i == 0xB6) printf("res  6,(hl)");
	else if (i == 0xB7) printf("res  6,a");
	else if (i == 0xB8) printf("res  7,b");
	else if (i == 0xB9) printf("res  7,c");
	else if (i == 0xBA) printf("res  7,d");
	else if (i == 0xBB) printf("res  7,e");
	else if (i == 0xBC) printf("res  7,h");
	else if (i == 0xBD) printf("res  7,l");
	else if (i == 0xBE) printf("res  7,(hl)");
	else if (i == 0xBF) printf("res  7,a");
	else if (i == 0xC0) printf("set  0,b");
	else if (i == 0xC1) printf("set  0,c");
	else if (i == 0xC2) printf("set  0,d");
	else if (i == 0xC3) printf("set  0,e");
	else if (i == 0xC4) printf("set  0,h");
	else if (i == 0xC5) printf("set  0,l");
	else if (i == 0xC6) printf("set  0,(hl)");
	else if (i == 0xC7) printf("set  0,a");
	else if (i == 0xC8) printf("set  1,b");
	else if (i == 0xC9) printf("set  1,c");
	else if (i == 0xCA) printf("set  1,d");
	else if (i == 0xCB) printf("set  1,e");
	else if (i == 0xCC) printf("set  1,h");
	else if (i == 0xCD) printf("set  1,l");
	else if (i == 0xCE) printf("set  1,(hl)");
	else if (i == 0xCF) printf("set  1,a");
	else if (i == 0xD0) printf("set  2,b");
	else if (i == 0xD1) printf("set  2,c");
	else if (i == 0xD2) printf("set  2,d");
	else if (i == 0xD3) printf("set  2,e");
	else if (i == 0xD4) printf("set  2,h");
	else if (i == 0xD5) printf("set  2,l");
	else if (i == 0xD6) printf("set  2,(hl)");
	else if (i == 0xD7) printf("set  2,a");
	else if (i == 0xD8) printf("set  3,b");
	else if (i == 0xD9) printf("set  3,c");
	else if (i == 0xDA) printf("set  3,d");
	else if (i == 0xDB) printf("set  3,e");
	else if (i == 0xDC) printf("set  3,h");
	else if (i == 0xDD) printf("set  3,l");
	else if (i == 0xDE) printf("set  3,(hl)");
	else if (i == 0xDF) printf("set  3,a");
	else if (i == 0xE0) printf("set  4,b");
	else if (i == 0xE1) printf("set  4,c");
	else if (i == 0xE2) printf("set  4,d");
	else if (i == 0xE3) printf("set  4,e");
	else if (i == 0xE4) printf("set  4,h");
	else if (i == 0xE5) printf("set  4,l");
	else if (i == 0xE6) printf("set  4,(hl)");
	else if (i == 0xE7) printf("set  4,a");
	else if (i == 0xE8) printf("set  5,b");
	else if (i == 0xE9) printf("set  5,c");
	else if (i == 0xEA) printf("set  5,d");
	else if (i == 0xEB) printf("set  5,e");
	else if (i == 0xEC) printf("set  5,h");
	else if (i == 0xED) printf("set  5,l");
	else if (i == 0xEE) printf("set  5,(hl)");
	else if (i == 0xEF) printf("set  5,a");
	else if (i == 0xF0) printf("set  6,b");
	else if (i == 0xF1) printf("set  6,c");
	else if (i == 0xF2) printf("set  6,d");
	else if (i == 0xF3) printf("set  6,e");
	else if (i == 0xF4) printf("set  6,h");
	else if (i == 0xF5) printf("set  6,l");
	else if (i == 0xF6) printf("set  6,(hl)");
	else if (i == 0xF7) printf("set  6,a");
	else if (i == 0xF8) printf("set  7,b");
	else if (i == 0xF9) printf("set  7,c");
	else if (i == 0xFA) printf("set  7,d");
	else if (i == 0xFB) printf("set  7,e");
	else if (i == 0xFC) printf("set  7,h");
	else if (i == 0xFD) printf("set  7,l");
	else if (i == 0xFE) printf("set  7,(hl)");
	else if (i == 0xFF) printf("set  7,a");
	else printf("INVALID INSTRUCTION: 0xCB 0x%02x", i);
}

void print_dd() {
	uint8_t i = next();
	if (i == 0x07) printf("ld   bc, (ix+0x%02x)", next());
	else if (i == 0x09) printf("add  ix, bc");
	else if (i == 0x0F) printf("ld   (ix+0x%02x), bc", next());
	else if (i == 0x17) printf("ld   de, (ix+0x%02x)", next());
	else if (i == 0x19) printf("add  ix, de");
	else if (i == 0x1F) printf("ld   (ix+0x%02x), de", next());
	else if (i == 0x21) printf("ld   ix, 0x%06x", next_value());
	else if (i == 0x22) printf("ld   (0x%06x), ix", next_value());
	else if (i == 0x23) printf("inc  ix");
	else if (i == 0x27) printf("ld   hl, (ix+0x%02x)", next());
	else if (i == 0x29) printf("add  ix, ix");
	else if (i == 0x2A) printf("ld   ix, (0x%06x)", next_value());
	else if (i == 0x2B) printf("dec  ix");
	else if (i == 0x2F) printf("ld   (ix+0x%02x), hl", next());
	else if (i == 0x31) printf("ld   iy, (ix+0x%02x)", next());
	else if (i == 0x34) printf("inc  (ix+0x%02x)", next());
	else if (i == 0x35) printf("dec  (ix+0x%02x)", next());
	else if (i == 0x36) printf("ld   (ix+0x%02x), 0x%02x", next(), next());
	else if (i == 0x37) printf("ld   ix, (ix+0x%02x)", next());
	else if (i == 0x39) printf("add  ix, sp");
	else if (i == 0x3E) printf("ld   (ix+0x%02x), iy", next());
	else if (i == 0x3F) printf("ld   (ix+0x%02x), ix", next());
	else if (i == 0x46) printf("ld   b, (ix+0x%02x)", next());
	else if (i == 0x4E) printf("ld   c, (ix+0x%02x)", next());
	else if (i == 0x56) printf("ld   d, (ix+0x%02x)", next());
	else if (i == 0x5E) printf("ld   e, (ix+0x%02x)", next());
	else if (i == 0x66) printf("ld   h, (ix+0x%02x)", next());
	else if (i == 0x6E) printf("ld   l, (ix+0x%02x)", next());
	else if (i == 0x70) printf("ld   (ix+0x%02x), b", next());
	else if (i == 0x71) printf("ld   (ix+0x%02x), c", next());
	else if (i == 0x72) printf("ld   (ix+0x%02x), d", next());
	else if (i == 0x73) printf("ld   (ix+0x%02x), e", next());
	else if (i == 0x74) printf("ld   (ix+0x%02x), h", next());
	else if (i == 0x75) printf("ld   (ix+0x%02x), l", next());
	else if (i == 0x77) printf("ld   (ix+0x%02x), a", next());
	else if (i == 0x7E) printf("ld   a, (ix+0x%02x)", next());
	else if (i == 0x86) printf("add  a, (ix+0x%02x)", next());
	else if (i == 0x8E) printf("adc  a, (ix+0x%02x)", next());
	else if (i == 0x96) printf("sub  a, (ix+0x%02x)", next());
	else if (i == 0x9E) printf("sbc  a, (ix+0x%02x)", next());
	else if (i == 0xA6) printf("and  (ix+0x%02x)", next());
	else if (i == 0xAE) printf("xor  (ix+0x%02x)", next());
	else if (i == 0xB6) printf("or   (ix+0x%02x)", next());
	else if (i == 0xBE) printf("cp   (ix+0x%02x)", next());
	else if (i == 0xCB) print_cb();
	else if (i == 0xE1) printf("pop  ix");
	else if (i == 0xE3) printf("ex   (sp),ix");
	else if (i == 0xE5) printf("push ix");
	else if (i == 0xE9) printf("jp   (ix)");
	else if (i == 0xF9) printf("ld   sp,ix");
	else printf("INVALID INSTRUCTION: 0xDD 0x%02x", i);
}

void print_ed() {
	uint8_t i = next();
	if (i == 0x00) printf("in0  b, 0x%02x", next());
	else if (i == 0x01) printf("out0 (0x%02x), b", next());
	else if (i == 0x02) printf("lea  bc, ix+0x%02x", next());
	else if (i == 0x03) printf("lea  bc, iy+0x%02x", next());
	else if (i == 0x04) printf("tst  a, b");
	else if (i == 0x07) printf("ld   bc, (hl)");
	else if (i == 0x08) printf("in0  c, (0x%02x)", next());
	else if (i == 0x09) printf("out0 (0x%02x), c", next());
	else if (i == 0x0C) printf("tst  a, c");
	else if (i == 0x0F) printf("ld   (hl), bc");
	else if (i == 0x10) printf("in0  d, (0x%02x)", next());
	else if (i == 0x11) printf("out0 (0x%02x), d", next());
	else if (i == 0x12) printf("lea  de, ix+0x%02x", next());
	else if (i == 0x13) printf("lea  de, iy+0x%02x", next());
	else if (i == 0x14) printf("tst  a, d");
	else if (i == 0x17) printf("ld   de, (hl)");
	else if (i == 0x18) printf("in0  e, (0x%02x)", next());
	else if (i == 0x19) printf("out0 (0x%02x), e", next());
	else if (i == 0x1C) printf("tst  a, e");
	else if (i == 0x1F) printf("ld   (hl), de");
	else if (i == 0x20) printf("in0  h, (0x%02x)", next());
	else if (i == 0x21) printf("out0 (0x%02x), h", next());
	else if (i == 0x22) printf("lea  hl, ix+0x%02x", next());
	else if (i == 0x23) printf("lea  hl, iy+0x%02x", next());
	else if (i == 0x24) printf("tst  a, h");
	else if (i == 0x27) printf("ld   hl, (hl)");
	else if (i == 0x28) printf("in0  l, (0x%02x)", next());
	else if (i == 0x29) printf("out0 (0x%02x), l", next());
	else if (i == 0x2C) printf("tst  a, l");
	else if (i == 0x2F) printf("ld   (hl), hl");
	else if (i == 0x31) printf("ld   iy, (hl)");
	else if (i == 0x32) printf("lea  ix, ix+0x%02x", next());
	else if (i == 0x33) printf("lea  iy, iy+0x%02x", next());
	else if (i == 0x34) printf("tst  a, (hl)");
	else if (i == 0x37) printf("ld   ix, (hl)");
	else if (i == 0x38) printf("in0  a, (0x%02x)", next());
	else if (i == 0x39) printf("out0 (0x%02x), a", next());
	else if (i == 0x3C) printf("tst  a, a");
	else if (i == 0x3E) printf("ld  (hl), iy");
	else if (i == 0x3F) printf("ld  (hl), ix");
	else if (i == 0x40) printf("in   b, (bc)");
	else if (i == 0x41) printf("out  (bc), b");
	else if (i == 0x42) printf("sbc  hl, bc");
	else if (i == 0x43) printf("ld   (0x%06x), bc", next_value());
	else if (i == 0x44) printf("neg");
	else if (i == 0x45) printf("retn    -- return from nom maskable input");
	else if (i == 0x46) printf("im   0    -- set interrupt mode 0");
	else if (i == 0x47) printf("ld   i, a");
	else if (i == 0x48) printf("in   c, (bc)");
	else if (i == 0x49) printf("out  (bc), c");
	else if (i == 0x4A) printf("adc  hl, bc");
	else if (i == 0x4B) printf("ld   bc, (0x%06x)", next_value());
	else if (i == 0x4C) printf("mult bc");
	else if (i == 0x4D) printf("reti");
	else if (i == 0x4F) printf("ld   r, a");
	else if (i == 0x50) printf("in   d, (bc)");
	else if (i == 0x51) printf("out  (bc), d");
	else if (i == 0x52) printf("sbc  hl, de");
	else if (i == 0x53) printf("ld   (0x%06x), de", next_value());
	else if (i == 0x54) printf("lea  ix, iy+0x%02x", next());
	else if (i == 0x55) printf("lea  iy, ix+0x%02x", next());
	else if (i == 0x56) printf("im   1    -- set interrupt mode 1");
	else if (i == 0x57) printf("ld   a, i");
	else if (i == 0x58) printf("in   e, (bc)");
	else if (i == 0x59) printf("out  (bc), e");
	else if (i == 0x5A) printf("adc  hl, de");
	else if (i == 0x5B) printf("ld   de, (0x%06x)", next_value());
	else if (i == 0x5C) printf("mult de");
	else if (i == 0x5E) printf("im   2");
	else if (i == 0x5F) printf("ld   a, r");
	else if (i == 0x60) printf("in   h, (bc)");
	else if (i == 0x61) printf("out  (bc), h");
	else if (i == 0x62) printf("sbc  hl, hl");
	else if (i == 0x63) printf("ld   (0x%06x), hl", next_value());
	else if (i == 0x64) printf("tst  a, 0x%02x", next());
	else if (i == 0x65) printf("pea  ix+0x%02x    -- push effective address", next());
	else if (i == 0x66) printf("pea  iy+0x%02x    -- push effective address", next());
	else if (i == 0x67) printf("rrd");
	else if (i == 0x68) printf("in   l, (bc)");
	else if (i == 0x69) printf("out  (bc) ,l");
	else if (i == 0x6A) printf("adc  hl, hl");
	else if (i == 0x6B) printf("ld   hl, (0x%06x)", next_value());
	else if (i == 0x6C) printf("mult hl");
	else if (i == 0x6D) printf("ld   mb,a");
	else if (i == 0x6E) printf("ld   a,mb");
	else if (i == 0x6F) printf("rld");
	else if (i == 0x72) printf("sbc  hl,sp");
	else if (i == 0x73) printf("ld   (0x%06x), sp", next_value());
	else if (i == 0x74) printf("tstio (0x%02x)", next());
	else if (i == 0x76) printf("slp");
	else if (i == 0x78) printf("in   a, (bc)");
	else if (i == 0x79) printf("out  (bc), a");
	else if (i == 0x7A) printf("adc  hl, sp");
	else if (i == 0x7B) printf("ld   sp, (0x%06x)", next_value());
	else if (i == 0x7C) printf("mult sp");
	else if (i == 0x7D) printf("stmix");
	else if (i == 0x7E) printf("rsmix");
	else if (i == 0x82) printf("inim");
	else if (i == 0x83) printf("otim");
	else if (i == 0x84) printf("ini2");
	else if (i == 0x8A) printf("indm");
	else if (i == 0x8B) printf("otdm");
	else if (i == 0x8C) printf("ind2");
	else if (i == 0x92) printf("inimr");
	else if (i == 0x93) printf("otimr");
	else if (i == 0x94) printf("ini2r");
	else if (i == 0x9A) printf("indmr");
	else if (i == 0x9B) printf("otdmr");
	else if (i == 0x9C) printf("ind2r");
	else if (i == 0xA0) printf("ldi");
	else if (i == 0xA1) printf("cpi");
	else if (i == 0xA2) printf("ini");
	else if (i == 0xA3) printf("oti");
	else if (i == 0xA4) printf("oti2");
	else if (i == 0xA8) printf("ldd");
	else if (i == 0xA9) printf("cpd");
	else if (i == 0xAA) printf("ind");
	else if (i == 0xAB) printf("otd");
	else if (i == 0xAC) printf("otd2");
	else if (i == 0xB0) printf("ldir");
	else if (i == 0xB1) printf("cpir");
	else if (i == 0xB2) printf("inir");
	else if (i == 0xB3) printf("otir");
	else if (i == 0xB4) printf("ori2r");
	else if (i == 0xB8) printf("lddr");
	else if (i == 0xB9) printf("cpdr");
	else if (i == 0xBA) printf("indr");
	else if (i == 0xBB) printf("otdr");
	else if (i == 0xBC) printf("otd2r");
	else printf("INVALID INSTRUCTION: 0xED 0x%02x", i);
}

void print_fd() {
	uint8_t i = next();
	if (i == 0x06) printf("rlc (iy+0x%02x)", next());
	else if (i == 0x07) printf("ld   bc, (iy+0x%02x)", next());
	else if (i == 0x09) printf("add  iy, bc");
	else if (i == 0x0E) printf("rrc (iy+0x%02x)", next());
	else if (i == 0x0F) printf("ld   (iy+0x%02x), bc", next());
	else if (i == 0x16) printf("rl  (iy+0x%02x)", next());
	else if (i == 0x17) printf("ld   de, (iy+0x%02x)", next());
	else if (i == 0x19) printf("add  iy, de");
	else if (i == 0x1F) printf("ld   (iy+0x%02x), de", next());
	else if (i == 0x1E) printf("rr  (iy+0x%02x)", next());
	else if (i == 0x21) printf("ld   iy, 0x%06x", next_value());
	else if (i == 0x22) printf("ld   (0x%06x), iy", next_value());
	else if (i == 0x23) printf("inc  iy");
	else if (i == 0x27) printf("ld   hl, (iy+0x%02x)", next());
	else if (i == 0x29) printf("add  iy, ix");
	else if (i == 0x2A) printf("ld   iy, (0x%06x)", next_value());
	else if (i == 0x2B) printf("dec  iy");
	else if (i == 0x26) printf("sla (iy+0x%02x)", next());
	else if (i == 0x2F) printf("ld   (iy+0x%02x), hl", next());
	else if (i == 0x31) printf("ld   ix, (iy+0x%02x)", next());
	else if (i == 0x34) printf("inc  (iy+0x%02x)", next());
	else if (i == 0x35) printf("dec  (iy+0x%02x)", next());
	else if (i == 0x36) printf("ld   (iy+0x%02x), 0x%02x", next(), next());
	else if (i == 0x37) printf("ld   iy, (ix+0x%02x)", next());
	else if (i == 0x2E) printf("sra (iy+0x%02x)", next());
	else if (i == 0x39) printf("add  iy, sp");
	else if (i == 0x3E) printf("srl (iy+0x%02x)", next());
	else if (i == 0x3F) printf("ld   (iy+0x%02x), ix", next());
	else if (i == 0x46) printf("bit 0, (iy+0x%02x)", next());
	else if (i == 0x4E) printf("bit 1, (iy+0x%02x)", next());
	else if (i == 0x56) printf("bit 2, (iy+0x%02x)", next());
	else if (i == 0x5E) printf("bit 3, (iy+0x%02x)", next());
	else if (i == 0x66) printf("bit 4, (iy+0x%02x)", next());
	else if (i == 0x6E) printf("bit 5, (iy+0x%02x)", next());
	else if (i == 0x70) printf("ld   (iy+0x%02x), b", next());
	else if (i == 0x71) printf("ld   (iy+0x%02x), c", next());
	else if (i == 0x72) printf("ld   (iy+0x%02x), d", next());
	else if (i == 0x73) printf("ld   (iy+0x%02x), e", next());
	else if (i == 0x74) printf("ld   (iy+0x%02x), h", next());
	else if (i == 0x75) printf("ld   (iy+0x%02x), l", next());
	else if (i == 0x76) printf("bit 6, (iy+0x%02x)", next());
	else if (i == 0x77) printf("ld   (iy+0x%02x), a", next());
	else if (i == 0x7E) printf("bit 7, (iy+0x%02x)", next());
	else if (i == 0x86) printf("res 0, (iy+0x%02x)", next());
	else if (i == 0x8E) printf("res 1, (iy+0x%02x)", next());
	else if (i == 0x96) printf("res 2, (iy+0x%02x)", next());
	else if (i == 0x9E) printf("res 3, (iy+0x%02x)", next());
	else if (i == 0xA6) printf("res 4, (iy+0x%02x)", next());
	else if (i == 0xAE) printf("res 5, (iy+0x%02x)", next());
	else if (i == 0xB6) printf("res 6, (iy+0x%02x)", next());
	else if (i == 0xBE) printf("res 7, (iy+0x%02x)", next());
	else if (i == 0xC6) printf("set 0, (iy+0x%02x)", next());
	else if (i == 0xCB) print_cb();
	else if (i == 0xCE) printf("set 1, (iy+0x%02x)", next());
	else if (i == 0xD6) printf("set 2, (iy+0x%02x)", next());
	else if (i == 0xDE) printf("set 3, (iy+0x%02x)", next());
	else if (i == 0xE1) printf("pop  iy");
	else if (i == 0xE3) printf("ex   (sp),iy");
	else if (i == 0xE5) printf("push iy");
	else if (i == 0xE6) printf("set 4, (iy+0x%02x)", next());
	else if (i == 0xEE) printf("set 5, (iy+0x%02x)", next());
	else if (i == 0xE9) printf("jp   (iy)");
	else if (i == 0xF6) printf("set 6, (iy+0x%02x)", next());
	else if (i == 0xFE) printf("set 7, (iy+0x%02x)", next());
	else if (i == 0xF9) printf("ld   sp,iy");
	else printf("INVALID INSTRUCTION: 0xFD 0x%02x", i);
}

/// read and print an instruction (without a new line)
void print_instruction() {
	uint8_t i = next();
	if (i == 0x00) printf("nop");
	else if (i == 0x01) printf("ld bc, 0x%06x", next_value());
	else if (i == 0x02) printf("ld (bc), a");
	else if (i == 0x03) printf("inc bc");
	else if (i == 0x04) printf("inc b");
	else if (i == 0x05) printf("dec b");
	else if (i == 0x06) printf("ld b, 0x%02x", next());
	else if (i == 0x07) printf("rlca    -- rotate left with carry accumulator");
	else if (i == 0x08) printf("ex af, af'");
	else if (i == 0x09) printf("add hl, bc");
	else if (i == 0x0a) printf("ld a, (bc)");
	else if (i == 0x0b) printf("dec db");
	else if (i == 0x0c) printf("inc c");
	else if (i == 0x0d) printf("dec c");
	else if (i == 0x0e) printf("ld c, 0x%02x", next());
	else if (i == 0x0f) printf("rrca    -- rotate right with carry accumulator");
	else if (i == 0x10) printf("djnz %hhi    -- decrement b, jump if not zero", next());
	else if (i == 0x11) printf("ld de, 0x%06x", next_value());
	else if (i == 0x12) printf("ld (de), a");
	else if (i == 0x13) printf("inc de");
	else if (i == 0x14) printf("inc d");
	else if (i == 0x15) printf("dec d");
	else if (i == 0x16) printf("ld d, 0x%02x", next());
	else if (i == 0x17) printf("rla    -- rotate left accumulator");
	else if (i == 0x18) printf("jr %hhi    -- jump relative", next());
	else if (i == 0x19) printf("add hl, de");
	else if (i == 0x1a) printf("ld a, (de)");
	else if (i == 0x1b) printf("dec de");
	else if (i == 0x1c) printf("inc e");
	else if (i == 0x1d) printf("dec e");
	else if (i == 0x1e) printf("ld e, 0x%02x", next());
	else if (i == 0x1f) printf("rra    -- rotate right accumulator");
	else if (i == 0x20) printf("jr nz, %hhi    -- jump relative if not zero", next());
	else if (i == 0x21) printf("ld hl, 0x%06x", next_value());
	else if (i == 0x22) printf("ld (0x%06x), hl", next_value());
	else if (i == 0x23) printf("inc hl");
	else if (i == 0x24) printf("inc h");
	else if (i == 0x25) printf("dec h");
	else if (i == 0x26) printf("ld h, 0x%02x", next());
	else if (i == 0x27) printf("daa    -- decimal adjust accumulator");
	else if (i == 0x28) printf("jr z, %hhi    -- jump relative if zero", next());
	else if (i == 0x29) printf("add hl, hl");
	else if (i == 0x2a) printf("ld hl, (0x%06x)", next_value());
	else if (i == 0x2b) printf("dec hl");
	else if (i == 0x2c) printf("inc l");
	else if (i == 0x2d) printf("dec l");
	else if (i == 0x2e) printf("ld l, 0x%02x", next());
	else if (i == 0x2f) printf("cpl    -- complement accumulator");
	else if (i == 0x30) printf("jr nc, %hhi    -- jump relative if not carry flag", next());
	else if (i == 0x31) printf("ld sp, 0x%06x", next_value());
	else if (i == 0x32) printf("ld (0x%06x), a", next_value());
	else if (i == 0x33) printf("inc sp");
	else if (i == 0x34) printf("inc (hl)");
	else if (i == 0x35) printf("dec (hl)");
	else if (i == 0x36) printf("ld (hl), 0x%02x", next());
	else if (i == 0x37) printf("scf    -- set carry flag");
	else if (i == 0x38) printf("jr c, %hhi    -- jump relative if carry flag", next());
	else if (i == 0x39) printf("add hl, sp");
	else if (i == 0x3a) printf("ld a, (0x%06x)", next_value());
	else if (i == 0x3b) printf("dec sp");
	else if (i == 0x3c) printf("inc a");
	else if (i == 0x3d) printf("dec a");
	else if (i == 0x3e) printf("ld a, 0x%02x", next());
	else if (i == 0x3f) printf("ccf    -- invert carry flag");
	else if (i == 0x40) {
		printf(".sis ");
		print_instruction();
	}
	else if (i == 0x41) printf("ld b, c");
	else if (i == 0x42) printf("ld b, d");
	else if (i == 0x43) printf("ld b, e");
	else if (i == 0x44) printf("ld b, h");
	else if (i == 0x45) printf("ld b, l");
	else if (i == 0x46) printf("ld b, (hl)");
	else if (i == 0x47) printf("ld b, a");
	else if (i == 0x48) printf("ld c, b");
	else if (i == 0x49) {
		printf(".lis ");
		print_instruction();
	}
	else if (i == 0x4a) printf("ld c, d");
	else if (i == 0x4b) printf("ld c, e");
	else if (i == 0x4c) printf("ld c, h");
	else if (i == 0x4d) printf("ld c, l");
	else if (i == 0x4e) printf("ld c, (hl)");
	else if (i == 0x4f) printf("ld c, a");
	else if (i == 0x50) printf("ld d, b");
	else if (i == 0x51) printf("ld d, c");
	else if (i == 0x52) {
		printf(".sil ");
		print_instruction();
	}
	else if (i == 0x53) printf("ld d, e");
	else if (i == 0x54) printf("ld d, h");
	else if (i == 0x55) printf("ld d, l");
	else if (i == 0x56) printf("ld d, (hl)");
	else if (i == 0x57) printf("ld d, a");
	else if (i == 0x58) printf("ld e, b");
	else if (i == 0x59) printf("ld e, c");
	else if (i == 0x5a) printf("ld e, d");
	else if (i == 0x5b) {
		printf(".lil ");
		print_instruction();
	}
	else if (i == 0x5c) printf("ld e, h");
	else if (i == 0x5d) printf("ld e, l");
	else if (i == 0x5e) printf("ld e, (hl)");
	else if (i == 0x5f) printf("ld e, a");
	else if (i == 0x60) printf("ld h, b");
	else if (i == 0x61) printf("ld h, c");
	else if (i == 0x62) printf("ld h, d");
	else if (i == 0x63) printf("ld h, e");
	else if (i == 0x64) printf("ld h, h");
	else if (i == 0x65) printf("ld h, l");
	else if (i == 0x66) printf("ld h, (hl)");
	else if (i == 0x67) printf("ld h, a");
	else if (i == 0x68) printf("ld l, b");
	else if (i == 0x69) printf("ld l, c");
	else if (i == 0x6a) printf("ld l, d");
	else if (i == 0x6b) printf("ld l, e");
	else if (i == 0x6c) printf("ld l, h");
	else if (i == 0x6d) printf("ld l, l");
	else if (i == 0x6e) printf("ld l, (hl)");
	else if (i == 0x6f) printf("ld l, a");
	else if (i == 0x70) printf("ld (hl), b");
	else if (i == 0x71) printf("ld (hl), c");
	else if (i == 0x72) printf("ld (hl), d");
	else if (i == 0x73) printf("ld (hl), e");
	else if (i == 0x74) printf("ld (hl), h");
	else if (i == 0x75) printf("ld (hl), l");
	else if (i == 0x76) printf("halt");
	else if (i == 0x77) printf("ld (hl), a");
	else if (i == 0x78) printf("ld a, b");
	else if (i == 0x79) printf("ld a, c");
	else if (i == 0x7a) printf("ld a, d");
	else if (i == 0x7b) printf("ld a, e");
	else if (i == 0x7c) printf("ld a, h");
	else if (i == 0x7d) printf("ld a, l");
	else if (i == 0x7e) printf("ld a, (hl)");
	else if (i == 0x7f) printf("ld a, a");
	else if (i == 0x80) printf("add a, b");
	else if (i == 0x81) printf("add a, c");
	else if (i == 0x82) printf("add a, d");
	else if (i == 0x83) printf("add a, e");
	else if (i == 0x84) printf("add a, h");
	else if (i == 0x85) printf("add a, l");
	else if (i == 0x86) printf("add a, (hl)");
	else if (i == 0x87) printf("add a, a");
	else if (i == 0x88) printf("adc a, b");
	else if (i == 0x89) printf("adc a, c");
	else if (i == 0x8a) printf("adc a, d");
	else if (i == 0x8b) printf("adc a, e");
	else if (i == 0x8c) printf("adc a, h");
	else if (i == 0x8d) printf("adc a, l");
	else if (i == 0x8e) printf("adc a, (hl)");
	else if (i == 0x8f) printf("adc a, a");
	else if (i == 0x90) printf("sub a, b");
	else if (i == 0x91) printf("sub a, c");
	else if (i == 0x92) printf("sub a, d");
	else if (i == 0x93) printf("sub a, e");
	else if (i == 0x94) printf("sub a, h");
	else if (i == 0x95) printf("sub a, l");
	else if (i == 0x96) printf("sub a, (hl)");
	else if (i == 0x97) printf("sub a, a");
	else if (i == 0x98) printf("sbc a, b");
	else if (i == 0x99) printf("sbc a, c");
	else if (i == 0x9a) printf("sbc a, d");
	else if (i == 0x9b) printf("sbc a, e");
	else if (i == 0x9c) printf("sbc a, h");
	else if (i == 0x9d) printf("sbc a, l");
	else if (i == 0x9e) printf("sbc a, (hl)");
	else if (i == 0x9f) printf("sbc a, a");
	else if (i == 0xa0) printf("and b");
	else if (i == 0xa1) printf("and c");
	else if (i == 0xa2) printf("and d");
	else if (i == 0xa3) printf("and e");
	else if (i == 0xA4) printf("and  a, h");
	else if (i == 0xA5) printf("and  a, l");
	else if (i == 0xA6) printf("and  a, (hl)");
	else if (i == 0xA7) printf("and  a, a");
	else if (i == 0xA8) printf("xor  a, b");
	else if (i == 0xA9) printf("xor  a, c");
	else if (i == 0xAA) printf("xor  a, d");
	else if (i == 0xAB) printf("xor  a, e");
	else if (i == 0xAC) printf("xor  a, h");
	else if (i == 0xAD) printf("xor  a, l");
	else if (i == 0xAE) printf("xor  a, (hl)");
	else if (i == 0xAF) printf("xor  a, a");
	else if (i == 0xB0) printf("or   a, b");
	else if (i == 0xB1) printf("or   a, c");
	else if (i == 0xB2) printf("or   a, d");
	else if (i == 0xB3) printf("or   a, e");
	else if (i == 0xB4) printf("or   a, h");
	else if (i == 0xB5) printf("or   a, l");
	else if (i == 0xB6) printf("or   a, (hl)");
	else if (i == 0xB7) printf("or   a, a");
	else if (i == 0xB8) printf("cp   a, b");
	else if (i == 0xB9) printf("cp   a, c");
	else if (i == 0xBA) printf("cp   a, d");
	else if (i == 0xBB) printf("cp   a, e");
	else if (i == 0xBC) printf("cp   a, h");
	else if (i == 0xBD) printf("cp   a, l");
	else if (i == 0xBE) printf("cp   a, (hl)");
	else if (i == 0xBF) printf("cp   a, a");
	else if (i == 0xC0) printf("ret  nz");
	else if (i == 0xC1) printf("pop  bc");
	else if (i == 0xC2) printf("jp   nz, 0x%06x", next_value());
	else if (i == 0xC3) printf("jp   0x%06x", next_value());
	else if (i == 0xC4) printf("call nz, 0x%06x", next_value());
	else if (i == 0xC5) printf("push bc");
	else if (i == 0xC6) printf("add  a, 0x%02x", next());
	else if (i == 0xC7) printf("rst  0x00");
	else if (i == 0xC8) printf("ret  z");
	else if (i == 0xC9) printf("ret");
	else if (i == 0xCA) printf("jp   z, 0x%06x", next_value());
	else if (i == 0xCB) print_cb();
	else if (i == 0xCC) printf("call z, 0x%06x", next_value());
	else if (i == 0xCD) printf("call 0x%06x", next_value());
	else if (i == 0xCE) printf("adc  a, 0x%02x", next());
	else if (i == 0xCF) printf("rst  0x08");
	else if (i == 0xD0) printf("ret  nc");
	else if (i == 0xD1) printf("pop  de");
	else if (i == 0xD2) printf("jp   nc, 0x%06x", next());
	else if (i == 0xD3) printf("out  (0x%02x), a", next());
	else if (i == 0xD4) printf("call nc, 0x%06x", next_value());
	else if (i == 0xD5) printf("push de");
	else if (i == 0xD6) printf("sub  a, 0x%02x", next());
	else if (i == 0xD7) printf("rst  0x10");
	else if (i == 0xD8) printf("ret  c");
	else if (i == 0xD9) printf("exx    -- exchange working register set with alternate");
	else if (i == 0xDA) printf("jp   c, 0x%06x", next_value());
	else if (i == 0xDB) printf("in   a, (0x%02x)", next());
	else if (i == 0xDC) printf("call c, 0x%06x", next_value());
	else if (i == 0xDD) print_dd();
	else if (i == 0xDE) printf("sbc  a, 0x%02x", next());
	else if (i == 0xDF) printf("rst  0x18");
	else if (i == 0xE0) printf("ret  po    -- return if parity odd");
	else if (i == 0xE1) printf("pop  hl");
	else if (i == 0xE2) printf("jp   po, 0x%06x    -- jump if parity odd", next_value());
	else if (i == 0xE3) printf("ex   (sp), hl");
	else if (i == 0xE4) printf("call po, 0x%06x    -- call if parity odd", next_value());
	else if (i == 0xE5) printf("push hl");
	else if (i == 0xE6) printf("and  a, 0x%02x", next());
	else if (i == 0xE7) printf("rst  0x20");
	else if (i == 0xE8) printf("ret  pe    -- return if parity even");
	else if (i == 0xE9) printf("jp   (hl)");
	else if (i == 0xEA) printf("jp   pe, 0x%06x    -- jump if parity even", next_value());
	else if (i == 0xEB) printf("ex   de, hl");
	else if (i == 0xEC) printf("call pe, 0x%06x    -- call if parity even", next_value());
	else if (i == 0xED) print_ed();
	else if (i == 0xEE) printf("xor  a, 0x%02x", next());
	else if (i == 0xEF) printf("rst  0x28");
	else if (i == 0xF0) printf("ret  p");
	else if (i == 0xF1) printf("pop  af");
	else if (i == 0xF2) printf("jp   p, 0x%06x    -- jump if positive", next_value());
	else if (i == 0xF3) printf("di    -- disable interrupt");
	else if (i == 0xF4) printf("call p, 0x%06x    -- call if positive", next_value());
	else if (i == 0xF5) printf("push af");
	else if (i == 0xF6) printf("or   a, 0x%02x", next());
	else if (i == 0xF7) printf("rst  0x30");
	else if (i == 0xF8) printf("ret  m    -- return if negative");
	else if (i == 0xF9) printf("ld   sp, hl");
	else if (i == 0xFA) printf("jp   m, 0x%06x    -- jump if negative", next_value());
	else if (i == 0xFB) printf("ei    -- enable interrupt");
	else if (i == 0xFC) printf("call m, 0x%06x    -- call if negative", next_value());
	else if (i == 0xFD) print_fd();
	else if (i == 0xFE) printf("cp   a, 0x%02x", next());
	else if (i == 0xFF) printf("rst  0x38");
	else printf("INVALID INSTRUCTION: 0x%02x", i);
}

int main() {
	while (1) {
		print_instruction();
		printf("\n");
	}

	return 0;
}
